### ISSUE TITLE
[Issue] Unable to Unload Lora

### ISSUE THREAD

**Issue by AsaTyr2018** [diStyApps/VisionCrafter#22]
Hey there,

once i created something with a lora attached. i can´t unload it.
Following creations without using a lora still cast for a lora file.

Exception in thread Thread-16 (animate_main_t):
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ai\AiMaster\AI\VisionCrafter\main.py", line 294, in animate_main_t
    animate_main(args,window)
  File "D:\ai\AiMaster\AI\VisionCrafter\repos\animatediff\scripts\animate.py", line 140, in main
    with safe_open(model_config.path, framework="pt", device="cpu") as f:
FileNotFoundError: No such file or directory: "D:\\ai\\AiMaster\\AI\\NextSD\\outputs\\text\\meguminKonosuba_v10.safetensors"

**Comment by diStyApps** [comment]
Yes i see, i broke something after setting models folder the option disappear, re launching VisualCrafter will fix it temporally.
I hope to release fix today.

**Comment by diStyApps** [comment]
Fixed, i hope its working properly now.

**Comment by AsaTyr2018** [comment]
Checked and working perfectly now =D Thank you
