### ISSUE TITLE
[Bug]: Open Folder buttons trigger a segmentation fault program crash

### ISSUE THREAD

**Issue by Ainaemaet** [diStyApps/VisionCrafter#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### Bug Description

When trying to click any of the 'Open Folder' options in the UI the program quits (though the UI remains visible and cannot be closed without shutting down my WSl2 instance), and I get the following error in the terminal: 

`Traceback (most recent call last):
  File "/home/myname/machinelearning/mediacreation/VisionCrafter/main.py", line 485, in <module>
    main()
  File "/home/myname/machinelearning/mediacreation/VisionCrafter/main.py", line 177, in main
    models_bar_layout.events(event,values,window)
  File "/home/myname/machinelearning/mediacreation/VisionCrafter/layout/models_bar.py", line 119, in events
    os.startfile(os.path.abspath(sg.user_settings_get_entry(MODEL_PATH)))
AttributeError: module 'os' has no attribute 'startfile'`

Running in WSL2 Ubuntu 20.04

### Step-by-step instructions to reproduce the issue.

Run the program with 'python main.py'
Opens UI. 
Click on any 'Open Folder' button (before or after a generation).
Program becomes unresponsive.
Check the terminal and see the above traceback and the program has terminated. 

### Expected Behavior

Clicking on the 'Open Folder' buttons should open a folder.

### Current Behavior

Clicking on the 'Open Folder' buttons crashes the program with the provided error.

### Version or Commit where the problem happens

Commit: 96b0582

### What platforms do you use Visioncrafter ?

Windows, Linux

### What Python version are you running on ?

3.10.12

### What GPU are you running Visioncrafter on?

RTX 4090

### How much GPU VRAM are you running Visioncrafter on?

24GB

### Console logs

```Shell
(visioncrafter) myname@MYPCNAME:~/machinelearning/mediacreation/VisionCrafter$ python main.py
Traceback (most recent call last):
  File "/home/myname/machinelearning/mediacreation/VisionCrafter/main.py", line 485, in <module>
    main()
  File "/home/myname/machinelearning/mediacreation/VisionCrafter/main.py", line 177, in main
    models_bar_layout.events(event,values,window)
  File "/home/myname/machinelearning/mediacreation/VisionCrafter/layout/models_bar.py", line 119, in events
    os.startfile(os.path.abspath(sg.user_settings_get_entry(MODEL_PATH)))
AttributeError: module 'os' has no attribute 'startfile'
```

### Additional information

Everything else seems to be working just fine. 
I have symlinked all model paths to a previous AnimateDiff install to save space.

**Comment by diStyApps** [comment]
I guess the main OS you using for VisionCrafter is Linux which is got limited support, on native windows all works as suggested on your posts.

It is mainly built on and for windows, so i barely tested on Linux.
Did try to run on native windows?
I will look in to it and make some improvements.

**Comment by Ainaemaet** [comment]
I didn't try to run on native windows (wanted to get it working in WSL2 as I keep all of my ML stuff there and a lot of what's currently out there is only fully-featured in linux). 

I'm looking through main.py and some documentation now and it appears os.startfile is windows only so I'm trying to find a linux equivalent or some other solution. 

Thank you for being willing to look into it, I'm sure a version of the gui that worked with WSL2 would be well-received as many people coming from other animatediff repos would be using that instead of windows! 
So far it's my favorite txt-to-video program out there next to tin2tin's generative-ai plugin for Blender.

**Comment by Ainaemaet** [comment]
I found this [universal-startfile](https://pypi.org/project/universal-startfile/) that might be of use. 
I tried getting it to work myself but now I'm getting a segmentation error but I'm still not quite used to python so...
