### ISSUE TITLE
Linux Support ？

### ISSUE THREAD

**Issue by zcdliuwei** [diStyApps/VisionCrafter#7]

**Comment by 15704080** [comment]
We need Linux Support

**Comment by 15704080** [comment]
I really need the linux support very much

**Comment by 15704080** [comment]
(venv) root@autodl-container-a1c3118008-79be1975:~/autodl-tmp/vision/VisionCrafter# python main.py
Traceback (most recent call last):
  File "/root/autodl-tmp/vision/VisionCrafter/main.py", line 910, in <module>
    main()
  File "/root/autodl-tmp/vision/VisionCrafter/main.py", line 304, in main
    window = sg.Window(f'{NAME} - {VER}',layout,finalize=True, resizable=True)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9618, in __init__
    self.Finalize()
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10304, in finalize
    self.Read(timeout=1)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10079, in read
    results = self._read(timeout=timeout, timeout_key=timeout_key)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10150, in _read
    self._Show()
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9890, in _Show
    StartupTK(self)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 16821, in StartupTK
    _get_hidden_master_root()
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 16708, in _get_hidden_master_root
    Window.hidden_master_root = tk.Tk()
  File "/root/miniconda3/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
(venv) root@autodl-container-a1c3118008-79be1975:~/autodl-tmp/vision/VisionCrafter#

**Comment by 15704080** [comment]
(venv) root@autodl-container-a1c3118008-79be1975:~/autodl-tmp/vision/VisionCrafter# python main.py
Traceback (most recent call last):
  File "/root/autodl-tmp/vision/VisionCrafter/main.py", line 910, in <module>
    main()
  File "/root/autodl-tmp/vision/VisionCrafter/main.py", line 304, in main
    window = sg.Window(f'{NAME} - {VER}',layout,finalize=True, resizable=True)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9618, in __init__
    self.Finalize()
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10304, in finalize
    self.Read(timeout=1)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10079, in read
    results = self._read(timeout=timeout, timeout_key=timeout_key)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10150, in _read
    self._Show()
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9890, in _Show
    StartupTK(self)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 16821, in StartupTK
    _get_hidden_master_root()
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 16708, in _get_hidden_master_root
    Window.hidden_master_root = tk.Tk()
  File "/root/miniconda3/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
(venv) root@autodl-container-a1c3118008-79be1975:~/autodl-tmp/vision/VisionCrafter#

**Comment by diStyApps** [comment]
It is working on Linux.
Install:
sudo apt install python3.10-venv
sudo apt-get install python3.10-tk && sudo apt install vlc
python3.10 -m venv venv 
source myenv/bin/activate
Run:
python3 main.py

if you use miniconda try to install "conda install tkinter", i am not sure didn't tested.

ill add proper support in the next updates.

**Comment by zcdliuwei** [comment]
> 

thanks again!!
