### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by 15704080** [diStyApps/VisionCrafter#8]
(venv) root@autodl-container-a1c3118008-79be1975:~/autodl-tmp/vision/VisionCrafter# python main.py
Traceback (most recent call last):
  File "/root/autodl-tmp/vision/VisionCrafter/main.py", line 910, in <module>
    main()
  File "/root/autodl-tmp/vision/VisionCrafter/main.py", line 304, in main
    window = sg.Window(f'{NAME} - {VER}',layout,finalize=True, resizable=True)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9618, in __init__
    self.Finalize()
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10304, in finalize
    self.Read(timeout=1)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10079, in read
    results = self._read(timeout=timeout, timeout_key=timeout_key)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10150, in _read
    self._Show()
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9890, in _Show
    StartupTK(self)
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 16821, in StartupTK
    _get_hidden_master_root()
  File "/root/autodl-tmp/vision/VisionCrafter/venv/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 16708, in _get_hidden_master_root
    Window.hidden_master_root = tk.Tk()
  File "/root/miniconda3/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
(venv) root@autodl-container-a1c3118008-79be1975:~/autodl-tmp/vision/VisionCrafter#

**Comment by 15704080** [comment]
we need
  File "/root/miniconda3/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by 15704080** [comment]
Thank you very sincerely. I will try it now

**Comment by 15704080** [comment]
It still doesn't seem to work,

**Comment by diStyApps** [comment]
What is the error?

**Comment by 15704080** [comment]
Is there a way for this to open it as a link

**Comment by AsaTyr2018** [comment]
> Is there a way for this to open it as a link?, I think it's very difficult to run GUI on Linux

depends on your linux os. if its a core version (Putty/SSH connection) then you are right. The Gui only opens on Linux if you utilise the Gui/Desktop it works. I testet it in a gnome Enviroment. Works but .... performance is a bit meh. 

Currently its Use the Native Python Interface. No webUI atm.

**Comment by AsaTyr2018** [comment]
Closed for Inactivity. If the question is still active, please open a new ticket and ref. to this:  Linux support #8
